### ISSUE TITLE
installation erases .bash_profile?

### ISSUE THREAD

**Issue by apoletayev** [joselado/quantum-lattice#1]
Hi! 
I tried installing this following the readme instructions. Mac os x 10.14.6, anaconda2, python 3.9.4. I used a pre-activated conda environment. After running the install ```python3 install.py``` and re-starting shell, my shell forgot where conda was. 

So I checked ~/.bash_profile and it only contained one line: ``` alias quantum-lattice="[conda environment]/python3 [GitHub folder]/quantum-lattice/pysrc/interpreter/../..//bin/quantum-lattice"```

Note that there is an extra / there.

I searched the cloned repo for where this could have been inserted into my profile, and found that in pycommand.py. So I think there may be a small bug in pycommand.py that erases the profile. (I am not sure whether the installation proceeded as otherwise expected)

Andrey

**Comment by joselado** [comment]
Hi apolatayev,

thanks a lot for bringing up this point and for the detailed info!

pycommand.py certainly tries to edit .bash_profile to add the quantum-lattice command, yet it checks in advance if there is text in the file to add the quantum-lattice info at the end. The reason why it may have overwritten the file could be that there was some error when reading the .bash_profile file (perhaps a non UTF-8 character).

I have made an update to the code, and now the code would append the quantum-lattice command to .bash_profile in any case.

The code should work after you had executed that command. If there was any further issue with the installation, please do not hesitate to let me know.

Thanks again for letting me know about this point!

Jose
