### ISSUE TITLE
Changing the path for plotting band structure

### ISSUE THREAD

**Issue by simran-chourasia** [joselado/quantum-lattice#3]
Hi, the quantum-lattice program plots the band structure of a honeycomb lattice along the path $\Gamma K M K' \Gamma$. But, I would like to get the band structure along $K \Gamma M K$ path. Is there a provision to change the path along which the band structure is calculated?

**Comment by joselado** [comment]
Hi simran-chourasia,

thanks for the message. In the quantum-lattice interface the path is given by default (it would be possible to change it). If you want to compute in a different path, you could use the pyqula library (which quantum-lattice uses), to compute the bands in any pth. You can see examples in the link below
https://github.com/joselado/jyvaskyla_summer_school_2022/blob/main/sessions/session1.ipynb

Best regards,
Jose
